version: 2.1

jobs:
  build_and_test_backend:
    docker:
      - image: circleci/python:3.7.4
    steps:
      - checkout
<<<<<<< HEAD
      - run: |
          pwd
          ls
          cd backend/
          ls
          python3 -m venv venv
          . venv/bin/activate
          pip install --no-cache-dir -r requirements.txt
          FLASK_APP=server.py
          python3 server_app.py &
jobs:
  run_tests:
    docker:
      - image: python:3.10   
    steps:
      - checkout
      - run:
          name: Install Python dependencies
          command: |
=======
      - run:
          name: Install Python dependencies
          command: |
            cd backend/
>>>>>>> 8375a39f91fd30f1b933b174dcbaf46670769420
            echo 'export PATH=~$PATH:~/.local/bin' >> $BASH_ENV && source $BASH_ENV
            pip install --user -r requirements.txt
      - run:
          name: Run unit tests
          command: |
            pytest --junitxml=test-reports/junit.xml --html=test-reports/pytest_report.html --self-contained-html
      - store_test_results:
          path: test-reports
      - store_artifacts:
<<<<<<< HEAD
          path: test-reports            
workflows: 
  Build:
      jobs:
        - build
        - run_tests
=======
          path: test-reports
    
  build_and_test_frontend:
      docker:
        - image: nginx
      steps:
        - checkout
        - run:
            name: copying file
            command: |
              cd frontend/
              cp -r ~/project/frontend/. /usr/share/nginx/html

workflows:
  build_test:
    jobs:
      - build_and_test_frontend
      - build_and_test_backend

>>>>>>> 8375a39f91fd30f1b933b174dcbaf46670769420
