version: 2.1
orbs:
  docker: circleci/docker@1.7.0
jobs:
  build:
    docker:
      - image: python:3.10      
    steps:
      - checkout
      - run: |
          pwd
          ls
          cd backend/
          ls
          python3 -m venv venv
          . venv/bin/activate
          pip install --no-cache-dir -r requirements.txt
          FLASK_APP=server.py
          python3 server_app.py &
jobs:
  run_tests:
    docker:
      - image: python:3.10   
    steps:
      - checkout
      - run:
          name: Install Python dependencies
          command: |
            echo 'export PATH=~$PATH:~/.local/bin' >> $BASH_ENV && source $BASH_ENV
            pip install --user -r requirements.txt
      - run:
          name: Run unit tests
          command: |
            pytest --junitxml=test-reports/junit.xml --html=test-reports/pytest_report.html --self-contained-html
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports            
workflows: 
  Build:
      jobs:
        - build
        - run_tests
