version: 2.1
orbs:
  docker: circleci/docker@1.7.0
jobs:
  build:
    docker:
      - image: python:3.10      
    steps:
      - checkout
      - run: |
          pwd
          ls
          cd backend/
          ls
          python3 -m venv venv
          . venv/bin/activate
          pip install --no-cache-dir -r requirements.txt
          FLASK_APP=server.py
          python3 server.py &
  test:
      - run:
          name: Run unit Tests
          command: |
            pytest --junixml=test-report/junit.xml --html=test-reports/pytest_report.html --self-contained-html
      - store_test_results
          path: test-reports
      - store_artifacts
          path: test-reports

             
workflows: 
  Build:
      jobs:
        - build
        - run_tests
